### ISSUE TITLE
Access token or store host is not valid!

### ISSUE THREAD

**Issue by hotmeteor** [lemonstand/lemonsync#14]
I have a config file setup for my site, and I'm certain my info is correct, yet I keep getting `Access token or store host is not valid!`.

Should `api_host` be pointing to a specific address? The docs say "The URI to LemonStand API"

running 0.0.18

**Comment by ChrisZieba** [comment]
The `api_host` is now your store domain, so if your store is hotmeteor.lemonstand.com the `api_host` would be `https://hotmeteor.lemonstand.com`.

**Comment by hotmeteor** [comment]
Hmm... this is what I have.

```
[api]
api_host = https://coastal.lemonstand.com
api_key = [api_key here]
api_access = [api_access here]

[dir]
watch_dir = /Users/Adam/Web/lscloud-theme-coastal
file_patterns = [ "*" ]
ignore_patterns = [ "*.tmp", "*.TMP", "*/.git*", "*.DS_STORE" ]

[store]
store_host = coastal.lemonstand.com
```

And my store:
![screen shot 2015-05-27 at 1 38 01 pm](https://cloud.githubusercontent.com/assets/378585/7844396/bc37f790-0475-11e5-9eac-00740616b784.png)

**Comment by ChrisZieba** [comment]
The api key may be expired, can you check in your store backend when the key was created.

**Comment by hotmeteor** [comment]
I had created a new one to try again:

```
Created: 2015-05-27 11:22:13
Expires: 2016-05-27 11:22:13
```

**Comment by hotmeteor** [comment]
Sorry, but any ideas? I can't really move forward until I get this working.

**Comment by ChrisZieba** [comment]
I fixed a bug with ssl verification that I think was causing this, can you grab the [latest version](https://pypi.python.org/pypi/lemonsync/0.1.19) and give it a try.

**Comment by hotmeteor** [comment]
Sorry, no. Same error.
Is there a way to add a debug/verbose flag so I can share error messages with more detail?

**Comment by ChrisZieba** [comment]
Can you email support your config file?

**Comment by hotmeteor** [comment]
Sent.

**Comment by hotmeteor** [comment]
Resolved. It was an issue with my user.

**Comment by robotpony** [comment]
@hotmeteor We'll make sure some better error messages get added for those failures in the future.

**Comment by jwalton512** [comment]
@hotmeteor could you advise what the issue with your user was?

i am running into the same error and can't seem to figure it out.

**Comment by daveaseeman** [comment]
@hotmeteor @ChrisZieba  could you post the solution? I have this problem also.

**Comment by jwalton512** [comment]
I just want to point out that my issue was resolved by lemonstand customer support.  Below is what he said:

Looks like there's an issue with Maintenance Mode and LemonSync together, so I've disabled Maintenance Mode in your store.

**Comment by daveaseeman** [comment]
That fixed it, thank you! Still hoping to get a more permanent fix from support.
