### ISSUE TITLE
Editing theme should be user-specific!

### ISSUE THREAD

**Issue by tomcornall** [lemonstand/lemonsync#19]
Editing theme is currently a user-specific setting in the `system_user_settings` table. However, lemonsync does not look at which user's theme setting it is making changes to. Lemonsync looks at the first user's `edit_theme` (in the `system_user_settings` table). 

This means whoever's user id comes first gets to choose the editing theme that Lemonsync looks at.

#### To improve:
- Make Lemonsync look at who's running the command

Option 1: Add a `user_email` setting to the .cfg to specify which user is running that Lemonsync command, can relate that to the `edit_theme` associated to that user.

**Comment by leahtard** [comment]
Thanks Tom! This will be super helpful for us at The Jibe as we usually develop with multiple dev's at the same time.

**Comment by tomcornall** [comment]
https://app.intercom.io/a/apps/7236196445273cea007287c0c90a2f0d598567cc/inbox/conversation/4773667912?nsrc=slack

Another instance here.
