### ISSUE TITLE
SSLError on Mac OS X

### ISSUE THREAD

**Issue by firozenazar** [lemonstand/lemonsync#37]
I'm using the lemonsync executable on Mac OSX 10.12.6. I've set up the config file as directed but I get a CERTIFICATE_VERIFY_FAILED error when I try to register the config file with lemonsync.

I don't know if this helps but the Python version on my Mac is 2.7.10

Thanks in advance for any help or guidance on this.

**Comment by tomcornall** [comment]
@firozenazar Thanks for the issue. We've rebuilt LemonSync recently, so please try the new version here:

https://github.com/lemonstand/lemonsync-js
