### ISSUE TITLE
Define the theme you want to sync with by setting API code in config

### ISSUE THREAD

**Issue by hotmeteor** [lemonstand/lemonsync#7]
Allow for an `api_code` value in the config file that would determine which theme you'll be syncing with. The API code would match the API code value that is set when you create a theme.

**Comment by bravomartin** [comment]
+1 

Another reason to do this: right now lemonsync only takes the main user's "currently editing" so if you are logged in with another user's account, even though you can change the "currently editing" theme, it doesn't affect the syncing theme. It took me some time to realize this. 

The use case I want it for is having a development theme, only used in preview mode, and a "production" one, syncing only stable versions of the theme. Controlling this via config files in my repo makes it less prone to error than doing it from the web interface.

**Comment by tomcornall** [comment]
@bravomartin The editing-theme is now tied to the user via API key -> log in as your secondary user and create a new API key, then select your editing-theme. If you use this new API key in your config file, LemonSync should watch changes for this specific user's editing-theme.

**Comment by bravomartin** [comment]
awesome thanks!

**Comment by bravomartin** [comment]
I hope even though you closed the issue, you're still considering the theme `api_code` option in the the lemonsync config file. That would be better than the current setup IMO.
